// <auto-generated />
namespace HotelManagementSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedPictureEntities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedPictureEntities));
        
        string IMigrationMetadata.Id
        {
            get { return "202001211002075_addedPictureEntities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
