// <auto-generated />
namespace HotelManagementSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class identityframeworkrefrence : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identityframeworkrefrence));
        
        string IMigrationMetadata.Id
        {
            get { return "202001120720425_identityframeworkrefrence"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
